import 'package:dartz/dartz.dart';
import 'package:afya_daktari_doctor/core/failures/failure.dart';

/// Autogenerated Code
/// Don't touch!
abstract class UseCaseBase<T1, T2> {
   Future<Either<Failure, T1>> call(T2 params);
}

